const tdengineKeys = [
    "SELECT",
    "DATABASE",
    "LIMIT",
    "SLIMIT",
    "PARTITION BY",
    "ORDER BY",
    "JOIN",
    "WHERE",
    "CASE",
    "WHEN",
    "ELSE",
    "FROM",
    "UNION ALL",
    "DISTINCT",
    "SESSION",
    "STATE_WINDOW",
    "INTERVAL",
    "SLIDING",
    "WATERMARK",
    "FILL",
    "GROUP BY",
    "_QSTART",
    "_QEND",
    "_WSTART",
    "_WEND",
    "_WDURATION",
    "_ROWTS",
    "_c0",
    "_IROWTS",
    "INDEX",
    "DELETE",

    "CREATE",
    "DATABASE",
    "IF NOT EXISTS",
    "BUFFER",
    "CACHEMODEL",
    "CACHESIZE",
    "DURATION",
    "WAL_FSYNC_PERIOD",
    "MAXROWS",
    "MINROWS",
    "KEEP",
    "PAGES",
    "PAGESIZE",
    "PRECISION",
    "REPLICA",
    "RETENTIONS",
    "WAL_LEVEL",
    "VGROUPS",
    "SINGLE_STABLE",
    "STT_TRIGGER",
    "TABLE_PREFIX",
    "TABLE_SUFFIX",
    "TSDB_PAGESIZE",
    "WAL_RETENTION_PERIOD",
    "WAL_RETENTION_SIZE",
    "WAL_SEGMENT_SIZE",
    "ALTER",
    "DROP",
    "TRIM DATABASE",
    "FLUSH DATABASE",
    "BALANCE VGROUP",

    "CREATE TABLE",
    "ALTER TABLE",
    "ADD COLUMN",
    "DROP COLUMN",
    "MODIFY COLUMN",
    "RENAME COLUMN",
    "CREATE STABLE",
    "SHOW STABLES",
    "DESCRIBE",
    "ADD TAG",
    "DROP TAG",
    "MODIFY TAG",
    "RENAME TAG",

    "INSERT INTO",
    "USING",
    "TAGS",
    "VALUES",

    "BINARY",
    "FLOAT",
    "TIMESTAMP",

    "SERVER_VERSION",
    "CLIENT_VERSION",
    "SERVER_STATUS",

    "NOW()",
    "TODAY()",
    "TIMEZONE()",

    "SHOW",
    "SHOW APPS",
    "SHOW CLUSTER",
    "SHOW CONNECTIONS",
    "SHOW CONSUMERS",
    "SHOW DATABASES",
    "SHOW DNODES",
    "SHOW MNODES",
    "SHOW QNODES",
    "SHOW FUNCTIONS",
    "SHOW LICENCES",
    "SHOW GRANTS",
    "SHOW INDEXES",
    "SHOW LOCAL VARIABLES",
    "SHOW QUERIES",
    "SHOW SCORES",
    "SHOW STREAMS",
    "SHOW SUBSCRIPTIONS",
    "SHOW TOPICS",
    "SHOW TRANSACTIONS",
    "SHOW USERS",
]

export default tdengineKeys
